User.create username: "pablo@pablo.com", password: "pablo", name: "Psoldier", admin: true
User.create username: "mariel@mariel.com", password: "mariel", name: "Mama"
User.create username: "mario@mario.com", password: "mario", name: "Msoldier"
User.create username: "juan@juan.com", password: "juan", name: "Jsoldier"
User.create username: "pedro@pedro.com", password: "pedro", name: "Pesoldier"
User.create username: "santiago@santiago.com", password: "santiago", name: "Ssoldier"
User.create username: "emilio@emilio.com", password: "emilio", name: "Esoldier"
User.create username: "daniel@daniel.com", password: "daniel", name: "Dsoldier"
User.create username: "ana@ana.com", password: "ana", name: "Asoldier"
User.create username: "elsa@elsa.com", password: "elsa", name: "Esoldier"
User.create username: "juancito@juancito.com", password: "juancito", name: "JAsoldier"
User.create username: "mali@mali.com", password: "mali", name: "Mmovi"
User.create username: "miga@miga.com", password: "miga", name: "Mimovi"
User.create username: "cecil@cecil.com", password: "cecil", name: "Cpibo"
User.create username: "valen@valen.com", password: "valen", name: "Vort"
User.create username: "oscar@oscar.com", password: "oscar", name: "Oort"